version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/grace-hopper-jeopardy
hooks:
  BeforeInstall:
    - location: deployment_scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: deployment_scripts/build_application
      timeout: 300
      runas: root
    - location: deployment_scripts/copy_application
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment_scripts/start_server
      timeout: 300
      runas: root
    - location: deployment_scripts/start_logging
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment_scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: deployment_scripts/validate_application
      timeout: 300
      runas: ec2-user
